#!/bin/bash

GIT_REPO=/site_repo.git
TMP_GIT_CLONE=/tmp/site_repo
PUBLIC_WWW=/usr/share/nginx/html

git clone $GIT_REPO $TMP_GIT_CLONE
jekyll build -s $TMP_GIT_CLONE -d $PUBLIC_WWW
rm -Rf $TMP_GIT_CLONE
exit
